{{- $root := . }}
{{- if and (not .Values.controller.JCasC.defaultConfig) (.Values.kubernetes.enabled) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jenkins.casc.configName" (list "jcasc-config" $ )}}
  namespace: {{ template "jenkins.namespace" $root }}
  labels:
    "app.kubernetes.io/name": {{ template "jenkins.name" $root}}
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    {{- end }}
    "app.kubernetes.io/managed-by": "{{ $.Release.Service }}"
    "app.kubernetes.io/instance": "{{ $.Release.Name }}"
    "app.kubernetes.io/component": "{{ $.Values.controller.componentName }}"
    {{ template "jenkins.fullname" $root }}-jenkins-config: "true"
data:
  jcasc-kubernetes-config.yaml: |-
    {{- include "jenkins.casc.kubernetes" . |nindent 4 }}
{{- end}}